#!/bin/bash
####################################################################################
# GRPO Training Script
# 
# Fine-tune HunyuanVideo model using the GRPO (Group Relative Policy Optimization) algorithm
#
# Input: 
#   - data_json_path: Preprocessed videos2caption.json file
#     (Generated by preprocess_hunyuan_text_embeddings.sh)
#
# Output:
#   - output_base_dir/checkpoint-{step}-{epoch}/diffusion_pytorch_model.safetensors
#   - output_base_dir/tensorboard/ (Training logs)
#
# Usage:
#   1. Run preprocess_hunyuan_text_embeddings.sh first to generate data
#   2. Modify the configuration parameters below
#   3. Run: bash scripts/train_grpo_hunyuan.sh
####################################################################################

####################################################################################
# Key Parameter Definitions - Please confirm before running
####################################################################################

# ==================== Root Directory Configuration (Must Modify) ====================
# Project root directory (the root of the Euphonium project)
WORKDIR="/path/to/Euphonium"
# ================================================================

# Conda environment configuration (please modify as needed)
conda_activate="/path/to/miniconda3/bin/activate"
conda_env_name="euphonium"

# ==================== Core Path Configuration (Must Modify) ====================
# HunyuanVideo model path
HUNYUAN_VIDEO_PATH="/path/to/HunyuanVideo"

# Reward model path
TRL_MODEL_PATH="/path/to/reward_model"

# Data path (videos2caption.json generated by preprocessing script)
# This path should be OUTPUT_DIR/videos2caption.json from preprocess_hunyuan_text_embeddings.sh
data_json_path="${WORKDIR}/assets/short_captions_merged_train.json"

# Checkpoint path (for resuming training, leave empty to start from scratch)
# To resume training, set this to the previous checkpoint directory
dit_model_name_or_path=""
# ================================================================

export PYTHONPATH=$PYTHONPATH:$WORKDIR

####################################################################################
# Reward Model Configuration
####################################################################################

# TRL prompt variant configuration (deformity_physics or ta)
TRL_PROMPT_VARIANT="deformity_physics"

# Whether to use the same noise
use_same_noise=true

TRL_CORE_ENABLED="true"  # Whether to enable the TRL Core reward model
TRL_MODEL_TYPE="InternVL3"
TRL_DTYPE="bf16"
TRL_PATH="${WORKDIR}/third_party/SoliReward"  # Path to SoliReward submodule (relative to project root)
TRL_TOKENIZER_PATH=""
SCORE_COEF="1.0"  # TRL Core reward weight

####################################################################################
# Video Parameter Configuration
####################################################################################

fps=8
num_frames=32
width=480
height=480
num_generations=8
sampling_steps=16

shift=5
timestep_fraction=0.6

# Timestep selection mode configuration
# mode: "fraction" - Select by proportion (using timestep_fraction)
#       "range" - Select by range (using start/end/interval)
timestep_selection_mode="fraction"
timestep_range_start=0    # range mode: starting step (0-indexed)
timestep_range_end=-1     # range mode: ending step (-1 for last)
timestep_range_interval=1 # range mode: step interval

####################################################################################
# Optional Reward Model Configuration (keep default values if not needed)
####################################################################################

# VideoAlign in TRL Reward configuration
VIDEO_ALIGN_IN_TRL_REWARD_ENABLED=false
VIDEO_ALIGN_IN_TRL_REWARD_PRETRAINED_PATH=""
VIDEO_ALIGN_IN_TRL_REWARD_USE_NORM=true
VIDEO_ALIGN_IN_TRL_REWARD_VQ_COEF="0.0"
VIDEO_ALIGN_IN_TRL_REWARD_MQ_COEF="0.0"
VIDEO_ALIGN_IN_TRL_REWARD_TA_COEF="0.0"

# Latent Reward in TRL Reward configuration
LATENT_REWARD_IN_TRL_REWARD_ENABLED="true"   # Whether to enable the Latent Reward Model
LATENT_REWARD_IN_TRL_REWARD_CHECKPOINT_DIR="/path/to/latent_reward_model" # Latent Reward Model checkpoint directory
LATENT_PRM_PATH="${WORKDIR}/third_party/Latent_PRM"        # Path to Latent_PRM submodule (relative to project root)
LATENT_REWARD_IN_TRL_REWARD_COEF="0.0"        # Latent Reward coefficient
LATENT_REWARD_IN_TRL_REWARD_DTYPE="bf16"      # Latent Reward Model data type
LATENT_REWARD_USE_SIGMOID="false"             # Whether to use Sigmoid to map Latent Reward output to [0,1]

# Process Latent Reward configuration (use reward gradient for guidance during denoising)
PROCESS_LATENT_REWARD_ENABLED="true"           # Main switch to control whether to load the Process Latent Reward model
PROCESS_LATENT_REWARD_SAMPLING_ENABLED="true"  # Whether to use reward gradient guidance during data collection (sampling)
PROCESS_LATENT_REWARD_TRAINING_ENABLED="false" # Whether to use reward gradient guidance during training
PROCESS_LATENT_REWARD_GUIDANCE_SCALE="0.01"      # Process Reward gradient guidance strength (set to 0.01, uses KL mode: scale = eta^2/(2*beta) = 0.0625/(2*3.125))
PROCESS_LATENT_REWARD_START_STEP="12"            # Step to start applying process reward (0-based)
PROCESS_LATENT_REWARD_END_STEP="-1"             # Step to stop applying process reward (-1 means until the end)
PROCESS_LATENT_REWARD_INTERVAL="1"              # Apply process reward every X steps
PROCESS_LATENT_REWARD_NORMALIZE_GRADIENT="false" # Whether to normalize the reward gradient
PROCESS_LATENT_REWARD_KL_BETA="3.125"           # KL divergence coefficient (beta = eta^2 / (2 * scale) = 0.0625 / (2 * 0.01) = 3.125)

# Process Reward for Advantage configuration
# mode: "none" - Use only Outcome Reward Advantage (ORA)
#       "only" - Use only Process Reward Advantage (PRA)
#       "both" - Weighted combination of ORA and PRA
PROCESS_REWARD_ADVANTAGE_MODE="both"            # Advantage calculation mode: none, only, both
PROCESS_REWARD_ADVANTAGE_COEF="1.0"             # PRA weight coefficient (used when mode=only or both)
OUTCOME_REWARD_ADVANTAGE_COEF="1.0"             # ORA weight coefficient (used when mode=both)

# KL Divergence Regularization configuration (prevents the trained model from deviating too far from the pretrained model)
USE_KL_LOSS="false"                               # Whether to enable KL divergence loss regularization
KL_COEF="3.125"                                 # KL weight coefficient (consistent with PROCESS_LATENT_REWARD_KL_BETA)
KL_TYPE="forward"                               # KL divergence type: forward (KL(policy||ref)), reverse, symmetric
KL_WEIGHT_VERSION="v2"                           # KL weight calculation version: v1 (Δt / η² · σ²) or v2 (Δt / 2η²) · (1 + η²(1-σ) / 2σ)²

# SPSA Reward Gradient Guidance configuration (disabled)
# SPSA (Simultaneous Perturbation Stochastic Approximation) zero-order optimization method
SPSA_REWARD_ENABLED="false"                      # Whether to enable SPSA reward gradient guidance
SPSA_REWARD_SIGMA="0.01"                        # SPSA perturbation coefficient σ, controlling random noise magnitude
SPSA_REWARD_GUIDANCE_SCALE="0.01"                # SPSA gradient scaling coefficient
SPSA_REWARD_NORMALIZE_GRADIENT="false"          # Whether to normalize the SPSA-estimated gradient
SPSA_REWARD_NUM_SAMPLES="1"                     # Number of random samples to estimate the gradient (more = accurate but slower)
SPSA_REWARD_START_STEP="12"                     # Step to start using SPSA reward
SPSA_REWARD_END_STEP="-1"                       # Step to stop using, -1 means until the end
SPSA_REWARD_INTERVAL="1"                        # Apply SPSA reward every X steps
SPSA_REWARD_KL_BETA="0.3125"                    # KL divergence coefficient

# Log Prob calculation control configuration
# Whether to use the mean incorporating reward gradient in log prob calculation
# true: Use reward-guided mean (sampling and log prob strictly consistent)
# false: Use mean WITHOUT reward guidance (sampling is guided but log prob is based on original distribution)
USE_REWARD_GUIDED_MEAN_FOR_LOGPROB="false"         # For sampling phase
USE_REWARD_GUIDED_MEAN_FOR_LOGPROB_TRAINING="false" # For training phase

# Whether to multiply reward/SPSA gradient by delta t
USE_DELTA_T_FOR_GRADIENT_SCALING="true"

# Set experiment name (to distinguish different training runs)
reward_model_specifier="LRM_general_v2-RGG_scale_${PROCESS_LATENT_REWARD_GUIDANCE_SCALE}_from_${PROCESS_LATENT_REWARD_START_STEP}_to_${PROCESS_LATENT_REWARD_END_STEP}-RGG_spl_${PROCESS_LATENT_REWARD_SAMPLING_ENABLED}_train_${PROCESS_LATENT_REWARD_TRAINING_ENABLED}-RGG_logp_mean_spl_${USE_REWARD_GUIDED_MEAN_FOR_LOGPROB}-train_${USE_REWARD_GUIDED_MEAN_FOR_LOGPROB_TRAINING}-RGG_dt_${USE_DELTA_T_FOR_GRADIENT_SCALING}-adv_${PROCESS_REWARD_ADVANTAGE_MODE}"

# Output directory (training results and checkpoints will be saved here)
output_base_dir="/path/to/output/${reward_model_specifier}"

# Torchrun launch configuration
USE_RDZV=false  # Whether to use rdzv mode for torchrun, default: false
# Automatically detect number of GPUs per node
export nproc_per_node=$(nvidia-smi --list-gpus | wc -l)
echo "Detected number of GPUs: $nproc_per_node"
export MASTER_PORT=12355  # Use different ports to avoid conflicts
hostfile="${hostfile:-/root/cur.hosts}"

# Network adapter configuration (to get the local IP address)
network_adapter="bond1"  # Specify network adapter name, modify according to actual environment

lr=1e-6

####################################################################################
# Pre-training Operations and Environment Preparation
####################################################################################
unset http_proxy
unset https_proxy

cd "$WORKDIR"
echo "work dir: $WORKDIR"

# Activate conda environment
if [ -f "$conda_activate" ]; then
    echo "Using conda activate: $conda_activate"
    echo "Using conda env name: $conda_env_name"
    source "$conda_activate" "$conda_env_name"
else
    echo "Warning: conda activate script not found at $conda_activate"
    echo "Please ensure the correct Python environment is activated"
fi

echo "master_port: $MASTER_PORT"

# Create logs directory
mkdir -p "${WORKDIR}/scripts/logs"

# Multi-node training configuration
if [ -f "$hostfile" ]; then
    # Read hostfile, filter valid lines (non-empty, non-comment), and sort
    readarray -t ips < <(grep -v '^#' "$hostfile" | grep -v '^$' | sort)
    
    # Use the first one as master
    MASTER_ADDR=${ips[0]}
    echo "master_addr: $MASTER_ADDR"
    
    # Set nnodes to the number of IPs
    nnodes=${#ips[@]}
    echo "nnodes: $nnodes"
    
    # Generate ip_to_rank mapping
    declare -A ip_to_rank
    for i in "${!ips[@]}"; do
        ip_to_rank[${ips[$i]}]=$i
    done
    
    # Get the local IP address (via specified adapter)
    current_ip=$(ip addr show $network_adapter | grep "inet " | awk '{print $2}' | cut -d/ -f1)
    echo "current ip: $current_ip"
    
    if [ -z "${ip_to_rank[$current_ip]}" ]; then
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        echo "WARNING: Current IP ($current_ip) not found in hostfile!"
        echo "This node may not be correctly identified in the distributed setup."
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    fi
    
    node_rank=${ip_to_rank[$current_ip]:-0}
    echo "node_rank = ${node_rank}"
else
    # Single-node training
    echo "No hostfile found, using single node configuration"
    MASTER_ADDR="localhost"
    nnodes=1
    node_rank=0
    current_ip="localhost"
fi

export nnodes=$nnodes
export MASTER_ADDR=$MASTER_ADDR

# Launch arguments for torchrun
if [ "$USE_RDZV" = "true" ]; then
    launch_args="
        --nproc_per_node $nproc_per_node \
        --nnodes $nnodes \
        --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
        --rdzv_id=dance_grpo_embedding \
        --rdzv_backend=c10d"
else
    launch_args="
        --nproc_per_node $nproc_per_node \
        --nnodes $nnodes \
        --node_rank $node_rank \
        --master_addr $MASTER_ADDR \
        --master_port $MASTER_PORT"
fi

# Create timestamped output directory
mkdir -p "${output_base_dir}"
mkdir -p "${output_base_dir}/tensorboard"
mkdir -p "${output_base_dir}/sh"
mkdir -p "${output_base_dir}/logs"

# Resume from Checkpoint: Copy previous TensorBoard files
if [ -n "$dit_model_name_or_path" ] && [ "$dit_model_name_or_path" != "" ]; then
    # Extract parent directory (previous training directory) from checkpoint path
    previous_train_dir=$(dirname "$dit_model_name_or_path")
    previous_tensorboard_dir="${previous_train_dir}/tensorboard"
    
    echo "Resume from checkpoint detected, path: $dit_model_name_or_path"
    echo "Previous training directory: $previous_train_dir"
    echo "Previous TensorBoard directory: $previous_tensorboard_dir"
    
    # Check if previous TensorBoard directory exists
    if [ -d "$previous_tensorboard_dir" ]; then
        echo "Found previous TensorBoard files, copying..."
        # Copy all TensorBoard event files to the new directory
        cp -r "${previous_tensorboard_dir}"/* "${output_base_dir}/tensorboard/" 2>/dev/null || true
        echo "✓ TensorBoard file copy complete, training curves will be continuous"
    else
        echo "⚠ Previous TensorBoard directory not found: $previous_tensorboard_dir"
        echo "  Starting TensorBoard from scratch"
    fi
fi

# Place log files in the logs subdirectory of the output directory
logs_path="${output_base_dir}/logs/hunyuanvideo_train_${current_ip}.txt"

# Save a copy of the script
cp $0 "${output_base_dir}/sh/"


####################################################################################
# Environment Variable Configuration - Adjust communication and debugging settings before training as needed
####################################################################################
# Basic NCCL settings
export NCCL_TIMEOUT=3600
export NCCL_IB_DISABLE=0
export NCCL_SOCKET_IFNAME=bond1
export NCCL_DEBUG=INFO
export TOKENIZERS_PARALLELISM=false


nohup torchrun $launch_args \
    "${WORKDIR}/scripts/train_grpo_hunyuan.py" \
    --seed 42 \
    --model_type "hunyuan_hf" \
    $(if [ -n "$dit_model_name_or_path" ] && [ "$dit_model_name_or_path" != "" ]; then echo "--dit_model_name_or_path $dit_model_name_or_path"; fi) \
    --pretrained_model_name_or_path "$HUNYUAN_VIDEO_PATH" \
    --vae_model_path "$HUNYUAN_VIDEO_PATH" \
    --cache_dir "${WORKDIR}/data/.cache" \
    --data_json_path "$data_json_path" \
    --gradient_checkpointing \
    --train_batch_size 1 \
    --sp_size 1 \
    --train_sp_batch_size 1 \
    --dataloader_num_workers 4 \
    --gradient_accumulation_steps 4 \
    --max_train_steps 501 \
    --learning_rate $lr \
    --mixed_precision bf16 \
    --checkpointing_steps 25 \
    --allow_tf32 \
    --cfg 0.0 \
    --output_dir "${output_base_dir}" \
    --h $height \
    --w $width \
    --t $num_frames \
    --sampling_steps $sampling_steps \
    --eta 0.25 \
    --lr_warmup_steps 0 \
    --fps $fps \
    --sampler_seed 1237 \
    --max_grad_norm 1.0 \
    --weight_decay 0.0001 \
    --num_generations $num_generations \
    --shift $shift \
    --use_group \
    --timestep_fraction $timestep_fraction \
    --timestep_selection_mode $timestep_selection_mode \
    --timestep_range_start $timestep_range_start \
    --timestep_range_end $timestep_range_end \
    --timestep_range_interval $timestep_range_interval \
    --use_same_noise $use_same_noise \
    --bestofn 8 \
    --reward_type trl \
    --trl_model_path "$TRL_MODEL_PATH" \
    --trl_model_type $TRL_MODEL_TYPE \
    --trl_tokenizer_path "$TRL_TOKENIZER_PATH" \
    --trl_dtype $TRL_DTYPE \
    --trl_path $TRL_PATH \
    --trl_core_enabled $TRL_CORE_ENABLED \
    --score_coef $SCORE_COEF \
    --trl_prompt_variant $TRL_PROMPT_VARIANT \
    --video_align_in_trl_reward_enabled $VIDEO_ALIGN_IN_TRL_REWARD_ENABLED \
    --video_align_in_trl_reward_pretrained_path "$VIDEO_ALIGN_IN_TRL_REWARD_PRETRAINED_PATH" \
    --video_align_in_trl_reward_use_norm $VIDEO_ALIGN_IN_TRL_REWARD_USE_NORM \
    --video_align_in_trl_reward_vq_coef $VIDEO_ALIGN_IN_TRL_REWARD_VQ_COEF \
    --video_align_in_trl_reward_ta_coef $VIDEO_ALIGN_IN_TRL_REWARD_TA_COEF \
    --video_align_in_trl_reward_mq_coef $VIDEO_ALIGN_IN_TRL_REWARD_MQ_COEF \
    --latent_reward_in_trl_reward_enabled $LATENT_REWARD_IN_TRL_REWARD_ENABLED \
    --latent_reward_in_trl_reward_checkpoint_dir "$LATENT_REWARD_IN_TRL_REWARD_CHECKPOINT_DIR" \
    --latent_prm_path "$LATENT_PRM_PATH" \
    --latent_reward_in_trl_reward_coef $LATENT_REWARD_IN_TRL_REWARD_COEF \
    --latent_reward_in_trl_reward_dtype $LATENT_REWARD_IN_TRL_REWARD_DTYPE \
    --latent_reward_use_sigmoid $LATENT_REWARD_USE_SIGMOID \
    --process_latent_reward_enabled $PROCESS_LATENT_REWARD_ENABLED \
    --process_latent_reward_sampling_enabled $PROCESS_LATENT_REWARD_SAMPLING_ENABLED \
    --process_latent_reward_training_enabled $PROCESS_LATENT_REWARD_TRAINING_ENABLED \
    --process_latent_reward_guidance_scale $PROCESS_LATENT_REWARD_GUIDANCE_SCALE \
    --process_latent_reward_start_step $PROCESS_LATENT_REWARD_START_STEP \
    --process_latent_reward_end_step $PROCESS_LATENT_REWARD_END_STEP \
    --process_latent_reward_interval $PROCESS_LATENT_REWARD_INTERVAL \
    --process_latent_reward_normalize_gradient $PROCESS_LATENT_REWARD_NORMALIZE_GRADIENT \
    --process_latent_reward_kl_beta $PROCESS_LATENT_REWARD_KL_BETA \
    --process_reward_advantage_mode $PROCESS_REWARD_ADVANTAGE_MODE \
    --process_reward_advantage_coef $PROCESS_REWARD_ADVANTAGE_COEF \
    --outcome_reward_advantage_coef $OUTCOME_REWARD_ADVANTAGE_COEF \
    --spsa_reward_enabled $SPSA_REWARD_ENABLED \
    --spsa_reward_sigma $SPSA_REWARD_SIGMA \
    --spsa_reward_guidance_scale $SPSA_REWARD_GUIDANCE_SCALE \
    --spsa_reward_normalize_gradient $SPSA_REWARD_NORMALIZE_GRADIENT \
    --spsa_reward_num_samples $SPSA_REWARD_NUM_SAMPLES \
    --spsa_reward_start_step $SPSA_REWARD_START_STEP \
    --spsa_reward_end_step $SPSA_REWARD_END_STEP \
    --spsa_reward_interval $SPSA_REWARD_INTERVAL \
    --spsa_reward_kl_beta $SPSA_REWARD_KL_BETA \
    --use_reward_guided_mean_for_logprob $USE_REWARD_GUIDED_MEAN_FOR_LOGPROB \
    --use_reward_guided_mean_for_logprob_training $USE_REWARD_GUIDED_MEAN_FOR_LOGPROB_TRAINING \
    --use_delta_t_for_gradient_scaling $USE_DELTA_T_FOR_GRADIENT_SCALING \
    --use_kl_loss $USE_KL_LOSS \
    --kl_coef $KL_COEF \
    --kl_type $KL_TYPE \
    --kl_weight_version $KL_WEIGHT_VERSION > "$logs_path" 2>&1 & 

echo ""
echo "=========================================="
echo "Training started in background"
echo "=========================================="
echo "Output directory: $output_base_dir"
echo "Log file: $logs_path"
echo ""
echo "After training, checkpoints will be saved at:"
echo "  ${output_base_dir}/checkpoint-{step}-{epoch}/"
echo ""
echo "Next step - Set in inference script:"
echo "  dit_model_name_or_path=\"${output_base_dir}/checkpoint-XXX-X/diffusion_pytorch_model.safetensors\""
echo "=========================================="